#!/usr/bin/env bash
#
# configure-autostart.sh — Create XDG autostart entries and helper scripts
#
# Provides:  configure_autostart
# Requires:  MOUNT_POINT  FREEFILESYNC_INSTALL_DIR  HOME
#

configure_autostart() {
    create_mount_helper
    create_sync_helper
    create_mount_desktop
    create_sync_desktop
}

# ---------------------------------------------------------------------------

create_mount_helper() {
    local helper_dir="${HOME}/.local/bin"
    local helper="${helper_dir}/mount-mailbox-drive"

    info "Creating mount helper script..."
    mkdir -p "${helper_dir}"

    cat > "${helper}" << MOUNTSCRIPT
#!/usr/bin/env bash
# Mount mailbox.org Drive with network wait.
# Generated by mailboxorg-drive-assistant — do not edit manually.

MOUNT_POINT="${MOUNT_POINT}"

# Already mounted?
if mountpoint -q "\${MOUNT_POINT}" 2>/dev/null; then
    exit 0
fi

# Wait up to 60 s for network connectivity
for _i in \$(seq 1 30); do
    if ping -c1 -W2 dav.mailbox.org &>/dev/null; then
        mount "\${MOUNT_POINT}"
        exit \$?
    fi
    sleep 2
done

echo "mount-mailbox-drive: network not available after 60 s" >&2
exit 1
MOUNTSCRIPT

    chmod +x "${helper}"
    ok "Mount helper: ${helper}"
}

# ---------------------------------------------------------------------------

create_sync_helper() {
    local helper_dir="${HOME}/.local/bin"
    local helper="${helper_dir}/start-realtimesync-mailbox"
    local real_file="${FREEFILESYNC_INSTALL_DIR}/BatchRun.ffs_real"
    local batch_file="${FREEFILESYNC_INSTALL_DIR}/BatchRun.ffs_batch"
    local rts_bin="${FREEFILESYNC_INSTALL_DIR}/RealTimeSync"

    info "Creating RealTimeSync helper script..."
    mkdir -p "${helper_dir}"

    cat > "${helper}" << SYNCSCRIPT
#!/usr/bin/env bash
# Start RealTimeSync for mailbox.org Drive sync.
# Generated by mailboxorg-drive-assistant — do not edit manually.

MOUNT_POINT="${MOUNT_POINT}"
REAL_FILE="${real_file}"
BATCH_FILE="${batch_file}"
RTS_BIN="${rts_bin}"

# Avoid duplicate instances
if pgrep -f "RealTimeSync.*BatchRun" >/dev/null 2>&1; then
    exit 0
fi

# Wait up to 90 s for the drive to be mounted
for _i in \$(seq 1 45); do
    mountpoint -q "\${MOUNT_POINT}" 2>/dev/null && break
    sleep 2
done

if ! mountpoint -q "\${MOUNT_POINT}" 2>/dev/null; then
    notify-send "RealTimeSync" "Drive not mounted at \${MOUNT_POINT}" 2>/dev/null || true
    echo "start-realtimesync-mailbox: drive not mounted" >&2
    exit 1
fi

if [[ ! -f "\${REAL_FILE}" ]]; then
    notify-send "RealTimeSync" "Config not found: \${REAL_FILE}" 2>/dev/null || true
    echo "start-realtimesync-mailbox: config missing: \${REAL_FILE}" >&2
    exit 1
fi

if [[ ! -f "\${BATCH_FILE}" ]]; then
    notify-send "RealTimeSync" "Batch file not found: \${BATCH_FILE}" 2>/dev/null || true
    echo "start-realtimesync-mailbox: batch file missing: \${BATCH_FILE}" >&2
    exit 1
fi

exec "\${RTS_BIN}" "\${REAL_FILE}"
SYNCSCRIPT

    chmod +x "${helper}"
    ok "Sync helper: ${helper}"
}

# ---------------------------------------------------------------------------

create_mount_desktop() {
    local autostart_dir="${HOME}/.config/autostart"
    local desktop_file="${autostart_dir}/mount-mailbox-drive.desktop"

    info "Creating mount autostart entry..."
    mkdir -p "${autostart_dir}"

    cat > "${desktop_file}" << DESKTOP
[Desktop Entry]
Type=Application
Name=Mount mailbox.org Drive
Comment=Mount mailbox.org WebDAV drive at login
Exec=${HOME}/.local/bin/mount-mailbox-drive
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
DESKTOP

    ok "Autostart entry: ${desktop_file}"
}

# ---------------------------------------------------------------------------

create_sync_desktop() {
    local autostart_dir="${HOME}/.config/autostart"
    local desktop_file="${autostart_dir}/realtimesync-mailbox.desktop"

    info "Creating RealTimeSync autostart entry..."
    mkdir -p "${autostart_dir}"

    cat > "${desktop_file}" << DESKTOP
[Desktop Entry]
Type=Application
Name=RealTimeSync — mailbox.org Drive
Comment=Synchronise local files with mailbox.org Drive
Exec=${HOME}/.local/bin/start-realtimesync-mailbox
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=5
DESKTOP

    ok "Autostart entry: ${desktop_file}"
}